### ISSUE TITLE
'tqdm' object has no attribute 'disable’ (users with Mac OS and Python3.7+ affected)

### ISSUE THREAD

**Issue by ccifuentesr** [3fon3fonov/exostriker#80]
When running MCMC I get an AttributeError: 'tqdm' object has no attribute 'disable’. This occurs in macOS (current version, 11.6) and Python >= 3.8. The error does not seem to arise in earlier versions of Python, in particular in 3.7.12.

**Comment by 3fon3fonov** [comment]
I am afraid this is a possible bug in 'tqdm'.  See https://github.com/tqdm/tqdm/issues/487

This seems to be out of my competence and I do not have the time to investigate in depth. I hope that the tqdm developers will fix this soon.


FYI, I cannot reproduce the problem under Linux/Ubuntu with Python3.8 and 3.9, but indeed the problem appears in Mac OS. I suspect this is somehow connected with how python3 handles multiprocessing/multithreading on  Mac OS.

A fix could be to simply tun-off the progress bar when running NS/MCMC

![test_progress_bar](https://user-images.githubusercontent.com/44244057/135713836-11c7bf0e-356e-4620-b6ed-7bc171815b7f.png)


git pull, and try again.

Please report if this is a potential workaround!

**Comment by ccifuentesr** [comment]
Unchecking MCMC progress bar seems to work in versions newer than Python 3.7.12. The MCMC analysis is performed while the Stdout/Stderr does not display any message.

The problem looks indeed within macOS and the handling of multiprocessing in Python3.8 and newer. [This thread](https://stackoverflow.com/questions/67796535/why-multiprocess-works-differently-in-ubuntu-vs-macos) in Stackoverflow supports this thesis, as I could reproduce both the problem and the solution.

**Comment by 3fon3fonov** [comment]
Any development on the "tqdm" side on this?

**Comment by ccifuentesr** [comment]
Looks like the thread regarding this issue ([tqdm/issues/487](https://github.com/tqdm/tqdm/issues/487)) is now closed, as brianbruggeman provided a working solution. Maybe this helps for now.

**Comment by 3fon3fonov** [comment]
This does not seem a general solution within tqdm. @ccifuentesr, when you have time, can you update your tqdm and Exo-Striker and try to reproduce the bug?

**Comment by 3fon3fonov** [comment]
This seems to be old and already fixed external bug, thus closing.
